language: java
jdk: oraclejdk11

sudo: false

install: true
script: ./mvnw clean install

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)

deploy:
  -
    on:
      branch: release
    provider: bintray
    skip_cleanup: true
    file: target/bin/bintray.json
    user: Ch35tEr
    key: $BINTRAY_API_KEY