language: java
jdk: oraclejdk11

sudo: false

install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - bash <(curl -s https://codecov.io/bash)
